language: php

php:
  - 7.3

#env:
#  matrix:
#    - COMPOSER_FLAGS="--prefer-lowest"
#    - COMPOSER_FLAGS=""

before_script:
  - printf "\n" | pecl install yaml
#  - travis_retry composer update ${COMPOSER_FLAGS}
  - travis_retry composer install

script:
  - vendor/bin/phpunit
