table: users

permissions:
  - criar usuario
  - editar usuario
  - listar usuarios
  - remover usuario

groups:
  - name: super admin
    permissions: '*'
    
  - name: admin
    permissions: 
      - listar usuarios
      - criar usuario  

views:
  - view: index
    title: Lista de usuários
    thead:
      - name
      - email
  
  - view: create
    title: Criar usuário
  
  - view: edit
    title: Editar usuário

schema:
  - field: id
    migration:
      primaryKey: true
    
  - field: name
    title: Nome
    migration:
      type: varchar
      limit: 255
    validator:
      - required
      - min:10

  - field: email
    title: E-mail
    migration:
      unique: true
      type: varchar
      limit: 255
    validator:
      - required
      - email

  - field: password
    title: Senha
    migration:
      type: varchar
      limit: 30
    validator:
      - required
      - max:30
      - confirm

  - field: confirmed_password
    title: Digite novamente a senha
    migration:
      type: varchar
      limit: 30
      only_validation: true

  - field: remember_token
    hidden: true
    migration:
      type: varchar
      limit: 120

  - field: email_verified_at
    hidden: true
    migration:
      type: varchar
      limit: 120
